//Create new property
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
export const ADD_PROPERTY_FAILURE = 'ADD_PROPERTY_FAILURE';
//Get Suburb suggestions
export const GET_SUBURB_SUGGESTIONS = 'GET_SUBURB_SUGGESTIONS';
export const UPDATE_SUBURB_SUGGESTION_INPUT_VALUE = 'UPDATE_SUBURB_SUGGESTION_INPUT_VALUE';
export const UPDATE_SUBURB_SUGGESTIONS = 'UPDATE_SUBURB_SUGGESTIONS';
export const CLEAR_SUBURB_SUGGESTIONS = 'CLEAR_SUBURB_SUGGESTIONS';